dir holding sqlite db need to be writable by Apache
The qunit jobs hits Apache which in turns need to be able to write to
the sqlite database.  Since the directory is not writable, sqlite bails
out:

    Query: INSERT  INTO l10n_cache (lc_lang,lc_key,lc_value) VALUES
    ('en','fallback','b:0;')
    Function: LCStore_DB::set/multi-row
    Error: 14 unable to open database file

Making the directory world writable should fix it.

Change-Id: I4ca968a3627b4310705a348f0a2cd54825d733a0