(bug 36167) Testswarm unable to open db file
When browsing testswarm snapshot, we had the nice error:

  Query: DELETE FROM l10n_cache WHERE lc_lang = 'en'
  Function: LCStore_DB::startWrite
  Error: 14 unable to open database file

Despite the sqlite file being set writable by the build.xml script. The
root cause is that SQLlite use the same directory as a temporary
directory and thus it needs g+w as well.

Change-Id: I4051f4ba5f103814326d78d09c0381ac555b9b55